// Generated by Copilot
const express = require('express');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3005;

// Serve static files from public directory
app.use(express.static(path.join(__dirname, 'public')));

// Serve node_modules for Saffron components and Font Awesome
app.use('/node_modules', express.static(path.join(__dirname, 'node_modules')));

// Middleware for parsing JSON and urlencoded form data
app.use(express.json());
app.use(express.urlencoded({ extended: false }));

// Routes
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});